"use client";

import { useState } from "react";
import DashboardLayout from "@/components/DashboardLayout";
import { mockHealthAlerts } from "@/data/mockData";
import { AlertTriangle, AlertCircle, ShieldCheck, ChevronLeft, ChevronRight, Leaf } from "lucide-react";

const ITEMS_PER_PAGE = 5;

export default function HealthAlertsPage() {
  const [severityFilter, setSeverityFilter] = useState("All Severities");
  const [page, setPage] = useState(1);

  const filtered = mockHealthAlerts.filter((a) => {
    if (severityFilter === "All Severities") return true;
    return a.severity === severityFilter.toLowerCase();
  });
  const totalPages = Math.max(1, Math.ceil(filtered.length / ITEMS_PER_PAGE));
  const paged = filtered.slice((page - 1) * ITEMS_PER_PAGE, page * ITEMS_PER_PAGE);

  const criticalCount = mockHealthAlerts.filter((a) => a.severity === "critical").length;
  const warningCount = mockHealthAlerts.filter((a) => a.severity === "warning").length;

  return (
    <DashboardLayout>
      <div className="mb-7">
        <h1 className="text-3xl font-bold text-gray-900">Health &amp; Care Alerts</h1>
        <p className="text-gray-500 mt-1 text-sm max-w-2xl">
          Monitor plants requiring immediate attention. Review critical health markers, environmental stress
          indicators, and urgent maintenance requests generated by the monitoring system.
        </p>
      </div>

      {/* Stat Cards */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6">
        <div className="bg-white rounded-xl shadow-sm border border-gray-100 border-l-4 border-l-red-500 p-4 flex items-center justify-between">
          <div>
            <p className="text-xs font-semibold text-gray-500 uppercase tracking-wider">Critical Alerts</p>
            <p className="text-3xl font-bold text-red-600 mt-1">{criticalCount}</p>
            <p className="text-xs text-red-500 mt-1 font-medium">+1 since yesterday</p>
          </div>
          <div className="w-12 h-12 rounded-full bg-red-100 flex items-center justify-center">
            <AlertCircle className="w-6 h-6 text-red-600" />
          </div>
        </div>
        <div className="bg-white rounded-xl shadow-sm border border-gray-100 border-l-4 border-l-amber-500 p-4 flex items-center justify-between">
          <div>
            <p className="text-xs font-semibold text-gray-500 uppercase tracking-wider">Warnings</p>
            <p className="text-3xl font-bold text-amber-600 mt-1">{warningCount}</p>
            <p className="text-xs text-amber-500 mt-1 font-medium">-3 since yesterday</p>
          </div>
          <div className="w-12 h-12 rounded-full bg-amber-100 flex items-center justify-center">
            <AlertTriangle className="w-6 h-6 text-amber-600" />
          </div>
        </div>
        <div className="bg-white rounded-xl shadow-sm border border-gray-100 border-l-4 border-l-green-500 p-4 flex items-center justify-between">
          <div>
            <p className="text-xs font-semibold text-gray-500 uppercase tracking-wider">Stable / Watchlist</p>
            <p className="text-3xl font-bold text-green-600 mt-1">39</p>
            <p className="text-xs text-green-500 mt-1 font-medium">Normal parameters</p>
          </div>
          <div className="w-12 h-12 rounded-full bg-green-100 flex items-center justify-center">
            <ShieldCheck className="w-6 h-6 text-green-600" />
          </div>
        </div>
      </div>

      {/* Alerts Table */}
      <div className="bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden">
        <div className="flex items-center justify-between px-5 py-4 border-b border-gray-100 flex-wrap gap-2">
          <h2 className="text-base font-semibold text-gray-800">Active Alerts</h2>
          <div className="flex items-center gap-2">
            <select value={severityFilter} onChange={(e) => { setSeverityFilter(e.target.value); setPage(1); }}
              className="px-3 py-1.5 border border-gray-200 rounded-lg text-xs focus:outline-none focus:ring-2 focus:ring-green-200 bg-white text-gray-700">
              <option>All Severities</option>
              <option>Critical</option>
              <option>Warning</option>
            </select>
            <select className="px-3 py-1.5 border border-gray-200 rounded-lg text-xs focus:outline-none focus:ring-2 focus:ring-green-200 bg-white text-gray-700">
              <option>All Issue Types</option>
              <option>Disease</option>
              <option>Environmental</option>
              <option>Watering</option>
            </select>
          </div>
        </div>

        <div className="overflow-x-auto">
          <table>
            <thead>
              <tr className="bg-gray-50 border-b border-gray-100">
                {["Alert Level", "Plant", "Issue", "Time Detected", "Action"].map((h) => (
                  <th key={h} className="px-5 py-3.5 text-left text-xs font-semibold text-gray-500 uppercase tracking-wider whitespace-nowrap">{h}</th>
                ))}
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100">
              {paged.map((alert) => (
                <tr key={alert.alert_id} className="hover:bg-gray-50 transition-colors">
                  {/* Alert Level */}
                  <td className="px-5 py-4">
                    <div className="flex items-center gap-1.5">
                      <span className={`w-2 h-2 rounded-full flex-shrink-0 ${alert.severity === "critical" ? "bg-red-500" : "bg-amber-500"}`} />
                      <span className={`badge ${alert.severity === "critical" ? "status-sick" : "status-recovering"}`}>
                        {alert.severity === "critical" ? "Critical" : "Warning"}
                      </span>
                    </div>
                  </td>
                  {/* Plant */}
                  <td className="px-5 py-4">
                    <div className="flex items-center gap-3">
                      <div className="w-9 h-9 rounded-full bg-gradient-to-br from-green-100 to-emerald-200 flex items-center justify-center flex-shrink-0">
                        <Leaf className="w-4 h-4 text-green-700" />
                      </div>
                      <div>
                        <p className="text-sm font-semibold text-gray-800">{alert.plant_name}</p>
                        <p className="text-xs text-gray-400 italic">{alert.scientific_name}</p>
                        <p className="text-xs font-mono text-gray-400">{alert.plant_id}</p>
                      </div>
                    </div>
                  </td>
                  {/* Issue */}
                  <td className="px-5 py-4 max-w-[220px]">
                    <p className="text-sm font-semibold text-gray-800">{alert.issue}</p>
                    <p className="text-xs text-gray-500 mt-0.5 leading-relaxed">{alert.description}</p>
                  </td>
                  {/* Time */}
                  <td className="px-5 py-4 text-xs text-gray-500 whitespace-nowrap">{alert.time_detected}</td>
                  {/* Action */}
                  <td className="px-5 py-4">
                    {alert.severity === "critical" ? (
                      <button className="px-3 py-1.5 bg-[#1B3B2C] hover:bg-[#14532d] text-white text-xs font-semibold rounded-lg transition whitespace-nowrap">
                        Log Care
                      </button>
                    ) : (
                      <button className="px-3 py-1.5 border border-gray-300 hover:bg-gray-50 text-gray-700 text-xs font-semibold rounded-lg transition whitespace-nowrap">
                        View Details
                      </button>
                    )}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {/* Pagination */}
        <div className="px-5 py-3.5 border-t border-gray-100 flex items-center justify-between">
          <p className="text-xs text-gray-500">Showing {Math.min((page - 1) * ITEMS_PER_PAGE + 1, filtered.length)}–{Math.min(page * ITEMS_PER_PAGE, filtered.length)} of {filtered.length} alerts</p>
          <div className="flex items-center gap-1">
            <button onClick={() => setPage(Math.max(1, page - 1))} disabled={page === 1} className="p-1.5 rounded hover:bg-gray-100 text-gray-500 disabled:opacity-40 transition"><ChevronLeft className="w-4 h-4" /></button>
            {Array.from({ length: totalPages }, (_, i) => (
              <button key={i} onClick={() => setPage(i + 1)} className={`w-7 h-7 rounded text-xs font-medium transition ${page === i + 1 ? "bg-[#1B3B2C] text-white" : "text-gray-600 hover:bg-gray-100"}`}>{i + 1}</button>
            ))}
            <button onClick={() => setPage(Math.min(totalPages, page + 1))} disabled={page === totalPages} className="p-1.5 rounded hover:bg-gray-100 text-gray-500 disabled:opacity-40 transition"><ChevronRight className="w-4 h-4" /></button>
          </div>
        </div>
      </div>
    </DashboardLayout>
  );
}
